/**
 * Google Fonts catalog — 1929 fonts with categories.
 *
 * Auto-generated from Google Fonts metadata API (2026-04-08).
 * Each entry is [fontFamily, category].
 * Sorted by popularity (most popular first).
 *
 * Categories: sans-serif, serif, display, handwriting, monospace
 *
 * The actual font files load from Google Fonts CDN on demand
 * (no API key needed). This file just provides the browsable catalog.
 */

export type FontCategory = 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace';

/** [fontFamily, category] — sorted by popularity */
export const GOOGLE_FONTS_CATALOG: [string, FontCategory][] = [
  ["Roboto", "sans-serif"],
  ["Open Sans", "sans-serif"],
  ["Google Sans", "sans-serif"],
  ["Inter", "sans-serif"],
  ["Montserrat", "sans-serif"],
  ["Poppins", "sans-serif"],
  ["Lato", "sans-serif"],
  ["Noto Sans JP", "sans-serif"],
  ["Roboto Condensed", "sans-serif"],
  ["Roboto Mono", "monospace"],
  ["Noto Sans", "sans-serif"],
  ["Arimo", "sans-serif"],
  ["Oswald", "sans-serif"],
  ["Raleway", "sans-serif"],
  ["Nunito", "sans-serif"],
  ["Nunito Sans", "sans-serif"],
  ["DM Sans", "sans-serif"],
  ["Playfair Display", "serif"],
  ["Rubik", "sans-serif"],
  ["Roboto Slab", "serif"],
  ["Ubuntu", "sans-serif"],
  ["Noto Sans KR", "sans-serif"],
  ["Merriweather", "serif"],
  ["Work Sans", "sans-serif"],
  ["PT Sans", "sans-serif"],
  ["Archivo Black", "sans-serif"],
  ["Kanit", "sans-serif"],
  ["Manrope", "sans-serif"],
  ["Outfit", "sans-serif"],
  ["Lora", "serif"],
  ["Mulish", "sans-serif"],
  ["Quicksand", "sans-serif"],
  ["Noto Sans TC", "sans-serif"],
  ["Inconsolata", "monospace"],
  ["Fjalla One", "sans-serif"],
  ["Figtree", "sans-serif"],
  ["Fira Sans", "sans-serif"],
  ["Barlow", "sans-serif"],
  ["Source Sans 3", "sans-serif"],
  ["Bebas Neue", "sans-serif"],
  ["Prompt", "sans-serif"],
  ["IBM Plex Sans", "sans-serif"],
  ["Saira", "sans-serif"],
  ["Titillium Web", "sans-serif"],
  ["Plus Jakarta Sans", "sans-serif"],
  ["Heebo", "sans-serif"],
  ["Jost", "sans-serif"],
  ["Karla", "sans-serif"],
  ["Noto Serif", "serif"],
  ["Archivo", "sans-serif"],
  ["PT Serif", "serif"],
  ["Bricolage Grotesque", "sans-serif"],
  ["Share Tech", "sans-serif"],
  ["Smooch Sans", "sans-serif"],
  ["Source Code Pro", "monospace"],
  ["Libre Baskerville", "serif"],
  ["Noto Color Emoji", "sans-serif"],
  ["Dancing Script", "handwriting"],
  ["Lobster Two", "display"],
  ["Cairo", "sans-serif"],
  ["Josefin Sans", "sans-serif"],
  ["Libre Franklin", "sans-serif"],
  ["Public Sans", "sans-serif"],
  ["EB Garamond", "serif"],
  ["Noto Serif JP", "serif"],
  ["Noto Sans SC", "sans-serif"],
  ["Barlow Condensed", "sans-serif"],
  ["Changa One", "display"],
  ["Nanum Gothic", "sans-serif"],
  ["Schibsted Grotesk", "sans-serif"],
  ["Dosis", "sans-serif"],
  ["Anton", "sans-serif"],
  ["Space Grotesk", "sans-serif"],
  ["Roboto Flex", "sans-serif"],
  ["Cabin", "sans-serif"],
  ["Bitter", "serif"],
  ["Noto Sans Telugu", "sans-serif"],
  ["Ramabhadra", "sans-serif"],
  ["Anek Telugu", "sans-serif"],
  ["Cormorant Garamond", "serif"],
  ["Inter Tight", "sans-serif"],
  ["Red Hat Display", "sans-serif"],
  ["Alfa Slab One", "display"],
  ["Assistant", "sans-serif"],
  ["Lexend", "sans-serif"],
  ["Slabo 27px", "serif"],
  ["Oxygen", "sans-serif"],
  ["Instrument Serif", "serif"],
  ["Gravitas One", "display"],
  ["Hind", "sans-serif"],
  ["Exo 2", "sans-serif"],
  ["Pacifico", "handwriting"],
  ["Sora", "sans-serif"],
  ["Tajawal", "sans-serif"],
  ["M PLUS Rounded 1c", "sans-serif"],
  ["Rajdhani", "sans-serif"],
  ["Urbanist", "sans-serif"],
  ["Lobster", "display"],
  ["Hind Siliguri", "sans-serif"],
  ["Arvo", "serif"],
  ["Crimson Text", "serif"],
  ["Comfortaa", "display"],
  ["Caveat", "handwriting"],
  ["PT Sans Narrow", "sans-serif"],
  ["DM Serif Display", "serif"],
  ["Google Sans Flex", "sans-serif"],
  ["JetBrains Mono", "monospace"],
  ["Merriweather Sans", "sans-serif"],
  ["Mukta", "sans-serif"],
  ["Bungee", "display"],
  ["Overpass", "sans-serif"],
  ["Source Serif 4", "serif"],
  ["Fredoka", "sans-serif"],
  ["Orbitron", "sans-serif"],
  ["Abel", "sans-serif"],
  ["Google Sans Code", "monospace"],
  ["DM Mono", "monospace"],
  ["Barlow Semi Condensed", "sans-serif"],
  ["IBM Plex Mono", "monospace"],
  ["Almarai", "sans-serif"],
  ["Chakra Petch", "sans-serif"],
  ["Teko", "sans-serif"],
  ["M PLUS 1p", "sans-serif"],
  ["Asap", "sans-serif"],
  ["Lexend Deca", "sans-serif"],
  ["Cinzel", "serif"],
  ["Domine", "serif"],
  ["Noto Sans Arabic", "sans-serif"],
  ["Satisfy", "handwriting"],
  ["Lilita One", "display"],
  ["Play", "sans-serif"],
  ["Varela Round", "sans-serif"],
  ["Shadows Into Light", "handwriting"],
  ["Maven Pro", "sans-serif"],
  ["Indie Flower", "handwriting"],
  ["Questrial", "sans-serif"],
  ["Geist", "sans-serif"],
  ["Bodoni Moda", "serif"],
  ["Abril Fatface", "display"],
  ["Zilla Slab", "serif"],
  ["Exo", "sans-serif"],
  ["IBM Plex Serif", "serif"],
  ["Instrument Sans", "sans-serif"],
  ["Kalam", "handwriting"],
  ["Fira Sans Condensed", "sans-serif"],
  ["IBM Plex Sans Arabic", "sans-serif"],
  ["Archivo Narrow", "sans-serif"],
  ["Noto Sans Thai", "sans-serif"],
  ["Marcellus", "serif"],
  ["Albert Sans", "sans-serif"],
  ["Be Vietnam Pro", "sans-serif"],
  ["Nanum Myeongjo", "serif"],
  ["Zen Kaku Gothic New", "sans-serif"],
  ["Onest", "sans-serif"],
  ["Space Mono", "monospace"],
  ["Titan One", "display"],
  ["Great Vibes", "handwriting"],
  ["Noto Serif KR", "serif"],
  ["Noto Kufi Arabic", "sans-serif"],
  ["Geologica", "sans-serif"],
  ["Cormorant", "serif"],
  ["Sofia Sans", "sans-serif"],
  ["Saira Condensed", "sans-serif"],
  ["Permanent Marker", "handwriting"],
  ["League Spartan", "sans-serif"],
  ["Unbounded", "sans-serif"],
  ["Luckiest Guy", "display"],
  ["ABeeZee", "sans-serif"],
  ["Encode Sans", "sans-serif"],
  ["Spectral", "serif"],
  ["Signika", "sans-serif"],
  ["Alumni Sans", "sans-serif"],
  ["Epilogue", "sans-serif"],
  ["Sarabun", "sans-serif"],
  ["Newsreader", "serif"],
  ["Fraunces", "serif"],
  ["Syne", "sans-serif"],
  ["Rowdies", "display"],
  ["Noto Serif TC", "serif"],
  ["Rethink Sans", "sans-serif"],
  ["Vollkorn", "serif"],
  ["Frank Ruhl Libre", "serif"],
  ["Roboto Serif", "serif"],
  ["Geist Mono", "monospace"],
  ["Catamaran", "sans-serif"],
  ["Alegreya", "serif"],
  ["Rubik Mono One", "sans-serif"],
  ["Bree Serif", "serif"],
  ["News Cycle", "sans-serif"],
  ["Antic Slab", "serif"],
  ["Asap Condensed", "sans-serif"],
  ["Noto Serif SC", "serif"],
  ["Literata", "serif"],
  ["Atkinson Hyperlegible", "sans-serif"],
  ["Libre Caslon Text", "serif"],
  ["Alegreya Sans", "sans-serif"],
  ["Montserrat Alternates", "sans-serif"],
  ["Unna", "serif"],
  ["Creepster", "display"],
  ["Sanchez", "serif"],
  ["Zen Maru Gothic", "sans-serif"],
  ["Righteous", "display"],
  ["Acme", "sans-serif"],
  ["Hanken Grotesk", "sans-serif"],
  ["Libre Barcode 39", "display"],
  ["Amiri", "serif"],
  ["DM Serif Text", "serif"],
  ["Cardo", "serif"],
  ["Hind Madurai", "sans-serif"],
  ["Prata", "serif"],
  ["Tinos", "serif"],
  ["Yanone Kaffeesatz", "sans-serif"],
  ["Hammersmith One", "sans-serif"],
  ["Noto Sans Display", "sans-serif"],
  ["Gothic A1", "sans-serif"],
  ["Crimson Pro", "serif"],
  ["Patua One", "display"],
  ["Chivo", "sans-serif"],
  ["Amatic SC", "handwriting"],
  ["Advent Pro", "sans-serif"],
  ["Bangers", "display"],
  ["Press Start 2P", "display"],
  ["Oleo Script", "display"],
  ["Viga", "sans-serif"],
  ["Readex Pro", "sans-serif"],
  ["Yellowtail", "handwriting"],
  ["Russo One", "sans-serif"],
  ["Changa", "sans-serif"],
  ["Baskervville", "serif"],
  ["Gruppo", "sans-serif"],
  ["Courier Prime", "monospace"],
  ["Comic Neue", "handwriting"],
  ["Kumbh Sans", "sans-serif"],
  ["Paytone One", "sans-serif"],
  ["Tenor Sans", "sans-serif"],
  ["Courgette", "handwriting"],
  ["Alata", "sans-serif"],
  ["Fira Code", "monospace"],
  ["Red Hat Text", "sans-serif"],
  ["Passion One", "display"],
  ["Shippori Mincho", "serif"],
  ["Aleo", "serif"],
  ["Noto Sans Devanagari", "sans-serif"],
  ["PT Sans Caption", "sans-serif"],
  ["Allura", "handwriting"],
  ["BIZ UDPGothic", "sans-serif"],
  ["Cantarell", "sans-serif"],
  ["Actor", "sans-serif"],
  ["Signika Negative", "sans-serif"],
  ["Sawarabi Mincho", "serif"],
  ["STIX Two Text", "serif"],
  ["Noto Naskh Arabic", "serif"],
  ["Martel", "serif"],
  ["League Gothic", "sans-serif"],
  ["Noticia Text", "serif"],
  ["Francois One", "sans-serif"],
  ["Kaushan Script", "handwriting"],
  ["Patrick Hand", "handwriting"],
  ["Lexend Giga", "sans-serif"],
  ["Fugaz One", "display"],
  ["Old Standard TT", "serif"],
  ["Crete Round", "serif"],
  ["Mitr", "sans-serif"],
  ["Sacramento", "handwriting"],
  ["Radio Canada", "sans-serif"],
  ["Delius", "handwriting"],
  ["Commissioner", "sans-serif"],
  ["Baloo 2", "display"],
  ["Noto Sans Tamil", "sans-serif"],
  ["Nanum Gothic Coding", "handwriting"],
  ["Didact Gothic", "sans-serif"],
  ["Golos Text", "sans-serif"],
  ["Yantramanav", "sans-serif"],
  ["Alexandria", "sans-serif"],
  ["Zeyada", "handwriting"],
  ["Sawarabi Gothic", "sans-serif"],
  ["Ubuntu Condensed", "sans-serif"],
  ["Philosopher", "sans-serif"],
  ["Playfair", "serif"],
  ["Quattrocento", "serif"],
  ["Rammetto One", "display"],
  ["Eczar", "serif"],
  ["Andada Pro", "serif"],
  ["Noto Sans Mono", "sans-serif"],
  ["Special Elite", "display"],
  ["IBM Plex Sans Condensed", "sans-serif"],
  ["Sen", "sans-serif"],
  ["PT Mono", "monospace"],
  ["Josefin Slab", "serif"],
  ["Rokkitt", "serif"],
  ["Gloria Hallelujah", "handwriting"],
  ["Chango", "display"],
  ["Noto Sans Bengali", "sans-serif"],
  ["Krub", "sans-serif"],
  ["Architects Daughter", "handwriting"],
  ["LINE Seed JP", "sans-serif"],
  ["Encode Sans Condensed", "sans-serif"],
  ["Amaranth", "sans-serif"],
  ["Khand", "sans-serif"],
  ["Saira Extra Condensed", "sans-serif"],
  ["Share Tech Mono", "monospace"],
  ["Eater", "display"],
  ["Berkshire Swash", "handwriting"],
  ["Sofia Sans Condensed", "sans-serif"],
  ["IBM Plex Sans JP", "sans-serif"],
  ["Parisienne", "handwriting"],
  ["Antonio", "sans-serif"],
  ["Cookie", "handwriting"],
  ["Oxanium", "display"],
  ["Bai Jamjuree", "sans-serif"],
  ["Sorts Mill Goudy", "serif"],
  ["Playfair Display SC", "serif"],
  ["Libre Bodoni", "serif"],
  ["Forum", "display"],
  ["Tangerine", "handwriting"],
  ["Gilda Display", "serif"],
  ["VT323", "monospace"],
  ["Noto Sans Hebrew", "sans-serif"],
  ["Kosugi Maru", "sans-serif"],
  ["Staatliches", "display"],
  ["Jura", "sans-serif"],
  ["Saira Semi Condensed", "sans-serif"],
  ["Monda", "sans-serif"],
  ["Zen Old Mincho", "serif"],
  ["Homemade Apple", "handwriting"],
  ["Lusitana", "serif"],
  ["Concert One", "display"],
  ["Quattrocento Sans", "sans-serif"],
  ["Gelasio", "serif"],
  ["Neuton", "serif"],
  ["Playball", "display"],
  ["Audiowide", "display"],
  ["El Messiri", "sans-serif"],
  ["Balsamiq Sans", "display"],
  ["Rock Salt", "handwriting"],
  ["Italianno", "handwriting"],
  ["Merienda", "handwriting"],
  ["M PLUS 1", "sans-serif"],
  ["Pathway Gothic One", "sans-serif"],
  ["Alex Brush", "handwriting"],
  ["Poiret One", "display"],
  ["Quantico", "sans-serif"],
  ["Faustina", "serif"],
  ["Lustria", "serif"],
  ["Reenie Beanie", "handwriting"],
  ["Macondo", "display"],
  ["Blinker", "sans-serif"],
  ["Mada", "sans-serif"],
  ["Gabarito", "display"],
  ["Istok Web", "sans-serif"],
  ["Amita", "handwriting"],
  ["Monoton", "display"],
  ["Ropa Sans", "sans-serif"],
  ["Arsenal", "sans-serif"],
  ["Biryani", "sans-serif"],
  ["Alice", "serif"],
  ["Nanum Pen Script", "handwriting"],
  ["Goldman", "display"],
  ["Handlee", "handwriting"],
  ["Pinyon Script", "handwriting"],
  ["Abhaya Libre", "serif"],
  ["Yeseva One", "display"],
  ["Cuprum", "sans-serif"],
  ["Calistoga", "display"],
  ["Anonymous Pro", "monospace"],
  ["Hind Guntur", "sans-serif"],
  ["Mukta Malar", "sans-serif"],
  ["Cedarville Cursive", "handwriting"],
  ["Cinzel Decorative", "display"],
  ["Volkhov", "serif"],
  ["Mr Dafoe", "handwriting"],
  ["Noto Nastaliq Urdu", "serif"],
  ["Noto Sans HK", "sans-serif"],
  ["Ubuntu Mono", "monospace"],
  ["Bad Script", "handwriting"],
  ["Andika", "sans-serif"],
  ["Cousine", "monospace"],
  ["Unica One", "display"],
  ["Black Han Sans", "sans-serif"],
  ["Dela Gothic One", "display"],
  ["Sofia Sans Extra Condensed", "sans-serif"],
  ["Noto Sans Symbols", "sans-serif"],
  ["Belanosima", "sans-serif"],
  ["Belleza", "sans-serif"],
  ["Hind Vadodara", "sans-serif"],
  ["Fira Mono", "monospace"],
  ["Noto Serif Bengali", "serif"],
  ["Nothing You Could Do", "handwriting"],
  ["Vidaloka", "serif"],
  ["Petrona", "serif"],
  ["Mona Sans", "sans-serif"],
  ["Wix Madefor Text", "sans-serif"],
  ["Noto Serif Display", "serif"],
  ["Cormorant Infant", "serif"],
  ["Caveat Brush", "handwriting"],
  ["Syncopate", "sans-serif"],
  ["Lateef", "serif"],
  ["Fira Sans Extra Condensed", "sans-serif"],
  ["Rakkas", "display"],
  ["Pangolin", "handwriting"],
  ["Cabin Condensed", "sans-serif"],
  ["Varela", "sans-serif"],
  ["Taviraj", "serif"],
  ["Gudea", "sans-serif"],
  ["Squada One", "display"],
  ["Ultra", "serif"],
  ["Sriracha", "handwriting"],
  ["GFS Didot", "serif"],
  ["Sofia", "handwriting"],
  ["Chewy", "display"],
  ["Arapey", "serif"],
  ["Itim", "handwriting"],
  ["Murecho", "sans-serif"],
  ["Ruda", "sans-serif"],
  ["Afacad", "sans-serif"],
  ["Lalezar", "sans-serif"],
  ["Reem Kufi", "sans-serif"],
  ["Michroma", "sans-serif"],
  ["Funnel Sans", "sans-serif"],
  ["Spline Sans", "sans-serif"],
  ["Racing Sans One", "display"],
  ["Pontano Sans", "sans-serif"],
  ["Averia Serif Libre", "display"],
  ["Black Ops One", "display"],
  ["Marck Script", "handwriting"],
  ["Akshar", "sans-serif"],
  ["Zen Kaku Gothic Antique", "sans-serif"],
  ["Reddit Sans", "sans-serif"],
  ["Wix Madefor Display", "sans-serif"],
  ["Martel Sans", "sans-serif"],
  ["Economica", "sans-serif"],
  ["Gochi Hand", "handwriting"],
  ["Carter One", "display"],
  ["Bowlby One SC", "display"],
  ["Ms Madi", "handwriting"],
  ["M PLUS 2", "sans-serif"],
  ["Damion", "handwriting"],
  ["Tilt Warp", "display"],
  ["IBM Plex Sans Thai", "sans-serif"],
  ["La Belle Aurore", "handwriting"],
  ["Leckerli One", "handwriting"],
  ["Jua", "sans-serif"],
  ["Niramit", "sans-serif"],
  ["Julius Sans One", "sans-serif"],
  ["Bevan", "serif"],
  ["Suez One", "serif"],
  ["Aboreto", "display"],
  ["Nixie One", "display"],
  ["Lemonada", "display"],
  ["Rozha One", "serif"],
  ["Khula", "sans-serif"],
  ["MuseoModerno", "display"],
  ["Mrs Saint Delafield", "handwriting"],
  ["Alegreya Sans SC", "sans-serif"],
  ["Boogaloo", "display"],
  ["Besley", "serif"],
  ["Noto Sans Malayalam", "sans-serif"],
  ["Sansita", "sans-serif"],
  ["Nanum Brush Script", "handwriting"],
  ["Allerta Stencil", "sans-serif"],
  ["Adamina", "serif"],
  ["Sarala", "sans-serif"],
  ["Londrina Solid", "display"],
  ["Anek Bangla", "sans-serif"],
  ["Covered By Your Grace", "handwriting"],
  ["Pirata One", "display"],
  ["Shippori Mincho B1", "serif"],
  ["Overpass Mono", "monospace"],
  ["Atkinson Hyperlegible Next", "sans-serif"],
  ["Yrsa", "serif"],
  ["Pridi", "serif"],
  ["Kaisei Decol", "serif"],
  ["BenchNine", "sans-serif"],
  ["Do Hyeon", "sans-serif"],
  ["Georama", "sans-serif"],
  ["Caprasimo", "display"],
  ["Bona Nova SC", "serif"],
  ["REM", "sans-serif"],
  ["Tomorrow", "sans-serif"],
  ["Shrikhand", "display"],
  ["Italiana", "sans-serif"],
  ["Whisper", "handwriting"],
  ["Kreon", "serif"],
  ["Judson", "serif"],
  ["Charm", "handwriting"],
  ["Corben", "display"],
  ["Just Another Hand", "handwriting"],
  ["Host Grotesk", "sans-serif"],
  ["Palanquin Dark", "sans-serif"],
  ["Pragati Narrow", "sans-serif"],
  ["Rufina", "serif"],
  ["Days One", "sans-serif"],
  ["ZCOOL QingKe HuangYou", "sans-serif"],
  ["Potta One", "display"],
  ["Hachi Maru Pop", "handwriting"],
  ["Grandstander", "display"],
  ["Mandali", "sans-serif"],
  ["Limelight", "display"],
  ["Secular One", "sans-serif"],
  ["Basic", "sans-serif"],
  ["Nova Square", "display"],
  ["Marcellus SC", "serif"],
  ["Sintony", "sans-serif"],
  ["Palanquin", "sans-serif"],
  ["Parkinsans", "sans-serif"],
  ["Fredericka the Great", "display"],
  ["K2D", "sans-serif"],
  ["Darker Grotesque", "sans-serif"],
  ["Cutive Mono", "monospace"],
  ["Kameron", "serif"],
  ["Coda", "display"],
  ["Kiwi Maru", "serif"],
  ["Ovo", "serif"],
  ["Ma Shan Zheng", "handwriting"],
  ["Vina Sans", "display"],
  ["Fahkwang", "sans-serif"],
  ["Neucha", "handwriting"],
  ["Cormorant Upright", "serif"],
  ["Athiti", "sans-serif"],
  ["Herr Von Muellerhoff", "handwriting"],
  ["Stardos Stencil", "display"],
  ["Nobile", "sans-serif"],
  ["Aclonica", "sans-serif"],
  ["Gloock", "serif"],
  ["Recursive", "sans-serif"],
  ["Laila", "serif"],
  ["Barriecito", "display"],
  ["Proza Libre", "sans-serif"],
  ["Castoro", "serif"],
  ["Goudy Bookletter 1911", "serif"],
  ["Krona One", "sans-serif"],
  ["Brygada 1918", "serif"],
  ["Karma", "serif"],
  ["Averia Libre", "display"],
  ["Yatra One", "display"],
  ["Mali", "handwriting"],
  ["Aldrich", "sans-serif"],
  ["Mate", "serif"],
  ["Yuji Mai", "serif"],
  ["Alef", "sans-serif"],
  ["BIZ UDGothic", "sans-serif"],
  ["Chonburi", "display"],
  ["Shadows Into Light Two", "handwriting"],
  ["Young Serif", "serif"],
  ["Ubuntu Sans", "sans-serif"],
  ["Inria Serif", "serif"],
  ["Livvic", "sans-serif"],
  ["Grand Hotel", "handwriting"],
  ["Oranienbaum", "serif"],
  ["Podkova", "serif"],
  ["Rye", "display"],
  ["Electrolize", "sans-serif"],
  ["Cabin Sketch", "display"],
  ["Klee One", "handwriting"],
  ["Caudex", "serif"],
  ["Baloo Da 2", "display"],
  ["Sniglet", "display"],
  ["Fustat", "sans-serif"],
  ["McLaren", "display"],
  ["PT Serif Caption", "serif"],
  ["Anek Latin", "sans-serif"],
  ["Norican", "handwriting"],
  ["Armata", "sans-serif"],
  ["Pattaya", "sans-serif"],
  ["Dongle", "sans-serif"],
  ["Familjen Grotesk", "sans-serif"],
  ["Amiko", "sans-serif"],
  ["Ysabeau Office", "sans-serif"],
  ["Candal", "sans-serif"],
  ["Metrophobic", "sans-serif"],
  ["Protest Revolution", "display"],
  ["Geo", "sans-serif"],
  ["Gantari", "sans-serif"],
  ["Lexend Exa", "sans-serif"],
  ["Oooh Baby", "handwriting"],
  ["Six Caps", "sans-serif"],
  ["DotGothic16", "sans-serif"],
  ["Radley", "serif"],
  ["Kosugi", "sans-serif"],
  ["Spinnaker", "sans-serif"],
  ["Allison", "handwriting"],
  ["Vazirmatn", "sans-serif"],
  ["Ephesis", "handwriting"],
  ["Glegoo", "serif"],
  ["Schoolbell", "handwriting"],
  ["Alatsi", "sans-serif"],
  ["Funnel Display", "display"],
  ["Anuphan", "sans-serif"],
  ["Gowun Batang", "serif"],
  ["Koulen", "display"],
  ["Rancho", "handwriting"],
  ["Chivo Mono", "monospace"],
  ["Telex", "sans-serif"],
  ["Libre Barcode 128", "display"],
  ["Wallpoet", "display"],
  ["Enriqueta", "serif"],
  ["Tiro Bangla", "serif"],
  ["ADLaM Display", "display"],
  ["Graduate", "serif"],
  ["Hepta Slab", "serif"],
  ["Bowlby One", "display"],
  ["Niconne", "handwriting"],
  ["Caladea", "serif"],
  ["Cantata One", "serif"],
  ["Montagu Slab", "serif"],
  ["SUSE", "sans-serif"],
  ["Pathway Extreme", "sans-serif"],
  ["Fragment Mono", "monospace"],
  ["Bungee Spice", "display"],
  ["RocknRoll One", "sans-serif"],
  ["Arbutus Slab", "serif"],
  ["Bellefair", "serif"],
  ["Annie Use Your Telescope", "handwriting"],
  ["Arizonia", "handwriting"],
  ["Glory", "sans-serif"],
  ["Dawning of a New Day", "handwriting"],
  ["UnifrakturMaguntia", "display"],
  ["Sometype Mono", "monospace"],
  ["Kristi", "handwriting"],
  ["Petit Formal Script", "handwriting"],
  ["Faster One", "display"],
  ["Allerta", "sans-serif"],
  ["Playpen Sans", "handwriting"],
  ["IBM Plex Sans KR", "sans-serif"],
  ["Jersey 25", "display"],
  ["Trirong", "serif"],
  ["Antic", "sans-serif"],
  ["Bellota Text", "display"],
  ["Rampart One", "display"],
  ["Antic Didone", "serif"],
  ["Coming Soon", "handwriting"],
  ["Halant", "serif"],
  ["ZCOOL XiaoWei", "sans-serif"],
  ["Major Mono Display", "monospace"],
  ["IM Fell English", "serif"],
  ["Jockey One", "sans-serif"],
  ["Knewave", "display"],
  ["Libre Barcode 39 Text", "display"],
  ["Azeret Mono", "monospace"],
  ["Edu SA Beginner", "handwriting"],
  ["Fjord One", "serif"],
  ["Oxygen Mono", "monospace"],
  ["Yesteryear", "handwriting"],
  ["Over the Rainbow", "handwriting"],
  ["Yusei Magic", "sans-serif"],
  ["Libre Caslon Display", "serif"],
  ["Fondamento", "handwriting"],
  ["Silkscreen", "display"],
  ["Sigmar One", "display"],
  ["Cairo Play", "sans-serif"],
  ["Cormorant SC", "serif"],
  ["Monsieur La Doulaise", "handwriting"],
  ["Honk", "display"],
  ["Montez", "handwriting"],
  ["Red Rose", "display"],
  ["Style Script", "handwriting"],
  ["Turret Road", "display"],
  ["Pixelify Sans", "display"],
  ["BioRhyme", "serif"],
  ["Sofia Sans Semi Condensed", "sans-serif"],
  ["Skranji", "display"],
  ["Radio Canada Big", "sans-serif"],
  ["Atma", "display"],
  ["Markazi Text", "serif"],
  ["Kantumruy Pro", "sans-serif"],
  ["Grenze Gotisch", "display"],
  ["Rosario", "sans-serif"],
  ["Kadwa", "serif"],
  ["Average Sans", "sans-serif"],
  ["Tilt Neon", "display"],
  ["Big Shoulders", "display"],
  ["Megrim", "display"],
  ["Bentham", "serif"],
  ["Calligraffitti", "handwriting"],
  ["Overlock", "display"],
  ["AR One Sans", "sans-serif"],
  ["Anton SC", "sans-serif"],
  ["Share", "sans-serif"],
  ["Waiting for the Sunrise", "handwriting"],
  ["Carlito", "sans-serif"],
  ["Noto Emoji", "sans-serif"],
  ["DynaPuff", "display"],
  ["Encode Sans Expanded", "sans-serif"],
  ["Marmelad", "sans-serif"],
  ["Zalando Sans Expanded", "sans-serif"],
  ["Noto Serif Hebrew", "serif"],
  ["Love Ya Like A Sister", "display"],
  ["Poller One", "display"],
  ["B612 Mono", "monospace"],
  ["Hina Mincho", "serif"],
  ["Cormorant Unicase", "serif"],
  ["Alegreya SC", "serif"],
  ["Lexend Peta", "sans-serif"],
  ["BIZ UDPMincho", "serif"],
  ["Hahmlet", "serif"],
  ["Irish Grover", "display"],
  ["Mountains of Christmas", "display"],
  ["Quintessential", "handwriting"],
  ["Flow Circular", "display"],
  ["Voces", "sans-serif"],
  ["Germania One", "display"],
  ["Mouse Memoirs", "sans-serif"],
  ["Maitree", "serif"],
  ["Freeman", "display"],
  ["Bubblegum Sans", "display"],
  ["Lekton", "monospace"],
  ["Gabriela", "serif"],
  ["Hurricane", "handwriting"],
  ["Mochiy Pop One", "sans-serif"],
  ["Ibarra Real Nova", "serif"],
  ["Noto Serif Khojki", "serif"],
  ["Agbalumo", "display"],
  ["IBM Plex Sans Hebrew", "sans-serif"],
  ["Noto Serif Devanagari", "serif"],
  ["Fauna One", "serif"],
  ["Agdasima", "sans-serif"],
  ["Charis SIL", "serif"],
  ["Croissant One", "display"],
  ["Noto Sans Myanmar", "sans-serif"],
  ["Encode Sans Semi Condensed", "sans-serif"],
  ["Noto Sans Georgian", "sans-serif"],
  ["Afacad Flux", "sans-serif"],
  ["Average", "serif"],
  ["Xanh Mono", "monospace"],
  ["Rochester", "handwriting"],
  ["Birthstone", "handwriting"],
  ["IM Fell English SC", "serif"],
  ["Fuzzy Bubbles", "handwriting"],
  ["Inria Sans", "sans-serif"],
  ["Trocchi", "serif"],
  ["Tektur", "display"],
  ["Bungee Inline", "display"],
  ["B612", "sans-serif"],
  ["Carrois Gothic", "sans-serif"],
  ["Rambla", "sans-serif"],
  ["Baloo Paaji 2", "display"],
  ["Mansalva", "handwriting"],
  ["Voltaire", "sans-serif"],
  ["Qwitcher Grypen", "handwriting"],
  ["Vujahday Script", "handwriting"],
  ["Kelly Slab", "display"],
  ["Noto Sans Sinhala", "sans-serif"],
  ["Bayon", "sans-serif"],
  ["Scada", "sans-serif"],
  ["Copse", "serif"],
  ["Marvel", "sans-serif"],
  ["Meddon", "handwriting"],
  ["Monomaniac One", "sans-serif"],
  ["Amarante", "display"],
  ["Seaweed Script", "display"],
  ["Baloo Thambi 2", "display"],
  ["Delius Unicase", "handwriting"],
  ["Spectral SC", "serif"],
  ["Sedgwick Ave Display", "handwriting"],
  ["Qwigley", "handwriting"],
  ["Syne Mono", "monospace"],
  ["Almendra", "serif"],
  ["Qahiri", "sans-serif"],
  ["WindSong", "handwriting"],
  ["Nova Mono", "monospace"],
  ["Baloo Chettan 2", "display"],
  ["Hanuman", "serif"],
  ["Anek Malayalam", "sans-serif"],
  ["Metamorphous", "display"],
  ["Farro", "sans-serif"],
  ["Encode Sans Semi Expanded", "sans-serif"],
  ["Sunflower", "sans-serif"],
  ["Baloo Bhaijaan 2", "display"],
  ["Meow Script", "handwriting"],
  ["Kalnia", "serif"],
  ["Special Gothic Expanded One", "sans-serif"],
  ["Manjari", "sans-serif"],
  ["Zen Antique", "serif"],
  ["Kaisei Opti", "serif"],
  ["Magra", "sans-serif"],
  ["Chelsea Market", "display"],
  ["Lacquer", "display"],
  ["Mallanna", "sans-serif"],
  ["Noto Sans Math", "sans-serif"],
  ["MedievalSharp", "display"],
  ["Red Hat Mono", "monospace"],
  ["Asul", "serif"],
  ["Corinthia", "handwriting"],
  ["Lexend Zetta", "sans-serif"],
  ["Rouge Script", "handwriting"],
  ["Solitreo", "handwriting"],
  ["Pompiere", "display"],
  ["Cal Sans", "sans-serif"],
  ["Rasa", "serif"],
  ["ZCOOL KuaiLe", "sans-serif"],
  ["Alike", "serif"],
  ["Vesper Libre", "serif"],
  ["Gluten", "display"],
  ["Vibur", "handwriting"],
  ["Noto Sans Khmer", "sans-serif"],
  ["Aguafina Script", "handwriting"],
  ["Odor Mean Chey", "serif"],
  ["IM Fell DW Pica", "serif"],
  ["David Libre", "serif"],
  ["Jomhuria", "display"],
  ["Boldonse", "display"],
  ["Miriam Libre", "sans-serif"],
  ["Kufam", "sans-serif"],
  ["Kurale", "serif"],
  ["Slackey", "display"],
  ["Prosto One", "display"],
  ["Denk One", "sans-serif"],
  ["Sarina", "display"],
  ["Balthazar", "serif"],
  ["Ribeye", "display"],
  ["Coustard", "serif"],
  ["Anybody", "display"],
  ["Quando", "serif"],
  ["Piazzolla", "serif"],
  ["Sue Ellen Francisco", "handwriting"],
  ["Oleo Script Swash Caps", "display"],
  ["Hubot Sans", "sans-serif"],
  ["Cambay", "sans-serif"],
  ["Capriola", "sans-serif"],
  ["Anek Devanagari", "sans-serif"],
  ["Baloo Tamma 2", "display"],
  ["KoHo", "sans-serif"],
  ["Give You Glory", "handwriting"],
  ["Sansita Swashed", "display"],
  ["Uncial Antiqua", "display"],
  ["Viaoda Libre", "display"],
  ["Thasadith", "sans-serif"],
  ["Platypi", "serif"],
  ["Tiro Devanagari Hindi", "serif"],
  ["Saira Stencil One", "display"],
  ["Orelega One", "display"],
  ["Akatab", "sans-serif"],
  ["Mr De Haviland", "handwriting"],
  ["Vast Shadow", "serif"],
  ["Gurajada", "sans-serif"],
  ["Madimi One", "sans-serif"],
  ["Modak", "display"],
  ["Aref Ruqaa", "serif"],
  ["Mukta Vaani", "sans-serif"],
  ["Noto Sans Oriya", "sans-serif"],
  ["Jaldi", "sans-serif"],
  ["Libre Barcode 39 Extended Text", "display"],
  ["Noto Serif HK", "serif"],
  ["Molengo", "sans-serif"],
  ["Contrail One", "display"],
  ["Amethysta", "serif"],
  ["Fontdiner Swanky", "display"],
  ["Poetsen One", "display"],
  ["Averia Sans Libre", "display"],
  ["Expletus Sans", "display"],
  ["Shantell Sans", "display"],
  ["Mukta Mahee", "sans-serif"],
  ["Euphoria Script", "handwriting"],
  ["Iceland", "display"],
  ["Inknut Antiqua", "serif"],
  ["Della Respira", "serif"],
  ["Cherry Bomb One", "display"],
  ["Lily Script One", "display"],
  ["Coiny", "display"],
  ["Allan", "display"],
  ["Battambang", "display"],
  ["Shojumaru", "display"],
  ["Julee", "handwriting"],
  ["Gaegu", "handwriting"],
  ["Gentium Plus", "serif"],
  ["Fanwood Text", "serif"],
  ["Bungee Shade", "display"],
  ["Solway", "serif"],
  ["Benne", "serif"],
  ["Mako", "sans-serif"],
  ["Codystar", "display"],
  ["Short Stack", "handwriting"],
  ["Zalando Sans", "sans-serif"],
  ["Doto", "sans-serif"],
  ["Hedvig Letters Serif", "serif"],
  ["Buenard", "serif"],
  ["Grape Nuts", "handwriting"],
  ["Orienta", "sans-serif"],
  ["Supermercado One", "display"],
  ["Square Peg", "handwriting"],
  ["Noto Serif Georgian", "serif"],
  ["Inder", "sans-serif"],
  ["Zen Antique Soft", "serif"],
  ["Gotu", "sans-serif"],
  ["Unkempt", "display"],
  ["Tienne", "serif"],
  ["Bellota", "display"],
  ["Salsa", "display"],
  ["Crafty Girls", "handwriting"],
  ["League Script", "handwriting"],
  ["Scheherazade New", "serif"],
  ["Just Me Again Down Here", "handwriting"],
  ["Esteban", "serif"],
  ["Arima", "display"],
  ["Walter Turncoat", "handwriting"],
  ["Happy Monkey", "display"],
  ["Brawler", "serif"],
  ["Doppio One", "sans-serif"],
  ["Meie Script", "handwriting"],
  ["Jersey 10", "display"],
  ["Asar", "serif"],
  ["Aladin", "display"],
  ["Finger Paint", "display"],
  ["Kodchasan", "sans-serif"],
  ["Iceberg", "display"],
  ["Cutive", "serif"],
  ["Bokor", "display"],
  ["Gowun Dodum", "sans-serif"],
  ["Yuji Syuku", "serif"],
  ["Cambo", "serif"],
  ["Zen Kurenaido", "sans-serif"],
  ["Phudu", "display"],
  ["Special Gothic Condensed One", "sans-serif"],
  ["Kranky", "display"],
  ["TikTok Sans", "sans-serif"],
  ["Zen Dots", "display"],
  ["Waterfall", "handwriting"],
  ["Numans", "sans-serif"],
  ["Gamja Flower", "handwriting"],
  ["Bigshot One", "display"],
  ["Freehand", "display"],
  ["New Rocker", "display"],
  ["Licorice", "handwriting"],
  ["Moon Dance", "handwriting"],
  ["The Girl Next Door", "handwriting"],
  ["Ruslan Display", "display"],
  ["Loved by the King", "handwriting"],
  ["Bilbo Swash Caps", "handwriting"],
  ["Oregano", "display"],
  ["Martian Mono", "monospace"],
  ["MonteCarlo", "handwriting"],
  ["Imprima", "sans-serif"],
  ["Abyssinica SIL", "serif"],
  ["Jaro", "sans-serif"],
  ["Lumanosimo", "handwriting"],
  ["Cherry Cream Soda", "display"],
  ["Geom", "sans-serif"],
  ["Poly", "serif"],
  ["Bakbak One", "display"],
  ["Rubik Dirt", "display"],
  ["Kablammo", "display"],
  ["Tenali Ramakrishna", "sans-serif"],
  ["Goblin One", "display"],
  ["Artifika", "serif"],
  ["Redressed", "handwriting"],
  ["Slabo 13px", "serif"],
  ["Sarpanch", "sans-serif"],
  ["Holtwood One SC", "serif"],
  ["Monofett", "monospace"],
  ["Noto Sans Meetei Mayek", "sans-serif"],
  ["Nova Round", "display"],
  ["Anaheim", "sans-serif"],
  ["Prociono", "serif"],
  ["Zain", "sans-serif"],
  ["Noto Sans Gujarati", "sans-serif"],
  ["Mina", "sans-serif"],
  ["Road Rage", "display"],
  ["Inclusive Sans", "sans-serif"],
  ["Puritan", "sans-serif"],
  ["Noto Sans Armenian", "sans-serif"],
  ["Wire One", "sans-serif"],
  ["Padauk", "sans-serif"],
  ["Wendy One", "sans-serif"],
  ["Nokora", "sans-serif"],
  ["Peralta", "serif"],
  ["IM Fell Double Pica", "serif"],
  ["Mirza", "serif"],
  ["Rubik Glitch", "display"],
  ["Elsie", "display"],
  ["Truculenta", "sans-serif"],
  ["Arya", "sans-serif"],
  ["Zhi Mang Xing", "handwriting"],
  ["Noto Sans Kannada", "sans-serif"],
  ["Sunshiney", "handwriting"],
  ["Stick No Bills", "sans-serif"],
  ["Train One", "display"],
  ["Shanti", "sans-serif"],
  ["Patrick Hand SC", "handwriting"],
  ["Charmonman", "handwriting"],
  ["Hi Melody", "handwriting"],
  ["Sumana", "serif"],
  ["NTR", "sans-serif"],
  ["Sedgwick Ave", "handwriting"],
  ["Noto Sans Thai Looped", "sans-serif"],
  ["Song Myung", "serif"],
  ["Baloo Bhai 2", "display"],
  ["Clicker Script", "handwriting"],
  ["Moul", "display"],
  ["Modern Antiqua", "display"],
  ["M PLUS 1 Code", "monospace"],
  ["Life Savers", "display"],
  ["Akronim", "display"],
  ["Swanky and Moo Moo", "handwriting"],
  ["Shippori Antique", "sans-serif"],
  ["Vollkorn SC", "serif"],
  ["Nata Sans", "sans-serif"],
  ["Federo", "sans-serif"],
  ["Teachers", "sans-serif"],
  ["Mochiy Pop P One", "sans-serif"],
  ["Dynalight", "display"],
  ["Angkor", "display"],
  ["Gulzar", "serif"],
  ["Galada", "display"],
  ["Rosarivo", "serif"],
  ["Rubik Wet Paint", "display"],
  ["Duru Sans", "sans-serif"],
  ["SN Pro", "sans-serif"],
  ["Fresca", "sans-serif"],
  ["Lemon", "display"],
  ["Sancreek", "display"],
  ["Crushed", "display"],
  ["Protest Strike", "display"],
  ["Aoboshi One", "serif"],
  ["Sevillana", "display"],
  ["Nosifer", "display"],
  ["Noto Serif Thai", "serif"],
  ["Reggae One", "display"],
  ["Alike Angular", "serif"],
  ["Spicy Rice", "display"],
  ["Borel", "handwriting"],
  ["Noto Sans Meroitic", "sans-serif"],
  ["Delicious Handrawn", "handwriting"],
  ["Trade Winds", "display"],
  ["Nerko One", "handwriting"],
  ["Carattere", "handwriting"],
  ["Harmattan", "sans-serif"],
  ["Frijole", "display"],
  ["IM Fell DW Pica SC", "serif"],
  ["Chicle", "display"],
  ["Genos", "sans-serif"],
  ["Maiden Orange", "serif"],
  ["Bubbler One", "sans-serif"],
  ["Emilys Candy", "display"],
  ["Suranna", "serif"],
  ["Original Surfer", "display"],
  ["Comic Relief", "display"],
  ["Long Cang", "handwriting"],
  ["Ledger", "serif"],
  ["Gemunu Libre", "sans-serif"],
  ["Kdam Thmor Pro", "sans-serif"],
  ["IM Fell French Canon", "serif"],
  ["Timmana", "sans-serif"],
  ["Beth Ellen", "handwriting"],
  ["Mooli", "sans-serif"],
  ["Fascinate", "display"],
  ["Eagle Lake", "handwriting"],
  ["Montaga", "serif"],
  ["Carme", "sans-serif"],
  ["Sail", "display"],
  ["IM Fell Great Primer", "serif"],
  ["Baloo Tammudu 2", "display"],
  ["Ceviche One", "display"],
  ["Spline Sans Mono", "monospace"],
  ["Dokdo", "display"],
  ["Special Gothic", "sans-serif"],
  ["Mohave", "sans-serif"],
  ["Zalando Sans SemiExpanded", "sans-serif"],
  ["Smooch", "handwriting"],
  ["Sour Gummy", "sans-serif"],
  ["Kaisei Tokumin", "serif"],
  ["BJ Cree", "serif"],
  ["Kavoon", "display"],
  ["Reddit Sans Condensed", "sans-serif"],
  ["Nova Flat", "display"],
  ["Manuale", "serif"],
  ["Birthstone Bounce", "handwriting"],
  ["Bona Nova", "serif"],
  ["Ysabeau SC", "sans-serif"],
  ["Shalimar", "handwriting"],
  ["Noto Sans Ethiopic", "sans-serif"],
  ["Nova Slim", "display"],
  ["Anek Tamil", "sans-serif"],
  ["Tauri", "sans-serif"],
  ["Baskervville SC", "serif"],
  ["Smythe", "display"],
  ["Noto Sans Lao", "sans-serif"],
  ["Noto Sans Symbols 2", "sans-serif"],
  ["Scope One", "serif"],
  ["Mystery Quest", "display"],
  ["IM Fell Double Pica SC", "serif"],
  ["Gayathri", "sans-serif"],
  ["Rubik Doodle Shadow", "display"],
  ["UnifrakturCook", "display"],
  ["Anta", "sans-serif"],
  ["Edu TAS Beginner", "handwriting"],
  ["Playwrite IE", "handwriting"],
  ["Vampiro One", "display"],
  ["Miniver", "display"],
  ["Akaya Kanadaka", "display"],
  ["Alkalami", "serif"],
  ["Asset", "display"],
  ["Gentium Book Plus", "serif"],
  ["Baumans", "display"],
  ["Lavishly Yours", "handwriting"],
  ["Kode Mono", "monospace"],
  ["Notable", "sans-serif"],
  ["Cactus Classical Serif", "serif"],
  ["Katibeh", "display"],
  ["Medula One", "display"],
  ["Comme", "sans-serif"],
  ["Yomogi", "handwriting"],
  ["Liu Jian Mao Cao", "handwriting"],
  ["Libre Barcode 128 Text", "display"],
  ["Averia Gruesa Libre", "display"],
  ["Metal Mania", "display"],
  ["Caesar Dressing", "display"],
  ["Flamenco", "display"],
  ["Astloch", "display"],
  ["Poltawski Nowy", "serif"],
  ["Milonga", "display"],
  ["Yeon Sung", "display"],
  ["Raleway Dots", "display"],
  ["Convergence", "sans-serif"],
  ["IBM Plex Sans Devanagari", "sans-serif"],
  ["IM Fell Great Primer SC", "serif"],
  ["Kenia", "display"],
  ["IM Fell French Canon SC", "serif"],
  ["Gugi", "display"],
  ["Homenaje", "sans-serif"],
  ["Kavivanar", "handwriting"],
  ["Atomic Age", "display"],
  ["Freckle Face", "display"],
  ["Overlock SC", "display"],
  ["Girassol", "display"],
  ["Protest Riot", "display"],
  ["Odibee Sans", "display"],
  ["Henny Penny", "display"],
  ["East Sea Dokdo", "handwriting"],
  ["Fuggles", "handwriting"],
  ["Rationale", "sans-serif"],
  ["Saira Stencil", "display"],
  ["Grenze", "serif"],
  ["Buda", "display"],
  ["Stalemate", "handwriting"],
  ["Miltonian Tattoo", "display"],
  ["Varta", "sans-serif"],
  ["Nova Cut", "display"],
  ["Rhodium Libre", "serif"],
  ["Rubik Bubbles", "display"],
  ["Barrio", "display"],
  ["Noto Serif Malayalam", "serif"],
  ["Miranda Sans", "sans-serif"],
  ["Gafata", "sans-serif"],
  ["Macondo Swash Caps", "display"],
  ["Sigmar", "display"],
  ["Sansation", "sans-serif"],
  ["Nova Script", "display"],
  ["Miltonian", "display"],
  ["Bonheur Royale", "handwriting"],
  ["Fasthand", "display"],
  ["Alkatra", "display"],
  ["Hedvig Letters Sans", "sans-serif"],
  ["Sulphur Point", "sans-serif"],
  ["Nova Oval", "display"],
  ["Cherry Swash", "display"],
  ["Playwrite US Trad", "handwriting"],
  ["Stick", "sans-serif"],
  ["Ruthie", "handwriting"],
  ["Imperial Script", "handwriting"],
  ["Chau Philomene One", "sans-serif"],
  ["Cantora One", "sans-serif"],
  ["Belgrano", "serif"],
  ["Delius Swash Caps", "handwriting"],
  ["Badeen Display", "display"],
  ["BhuTuka Expanded One", "serif"],
  ["Pavanam", "sans-serif"],
  ["The Nautigal", "handwriting"],
  ["Kulim Park", "sans-serif"],
  ["Jolly Lodger", "display"],
  ["Baloo Bhaina 2", "display"],
  ["Habibi", "serif"],
  ["Noto Music", "sans-serif"],
  ["Finlandica", "sans-serif"],
  ["Zilla Slab Highlight", "serif"],
  ["Stylish", "sans-serif"],
  ["Englebert", "sans-serif"],
  ["Imbue", "serif"],
  ["Single Day", "display"],
  ["Lexend Mega", "sans-serif"],
  ["Headland One", "serif"],
  ["Island Moments", "handwriting"],
  ["Handjet", "display"],
  ["Mynerve", "handwriting"],
  ["Gupter", "serif"],
  ["Srisakdi", "display"],
  ["Jomolhari", "serif"],
  ["Strait", "sans-serif"],
  ["Khmer", "sans-serif"],
  ["Darumadrop One", "display"],
  ["Cascadia Code", "sans-serif"],
  ["Kapakana", "handwriting"],
  ["Unlock", "display"],
  ["Ranchers", "display"],
  ["Redacted", "display"],
  ["Luxurious Script", "handwriting"],
  ["Marhey", "display"],
  ["Chathura", "sans-serif"],
  ["Winky Sans", "sans-serif"],
  ["Alan Sans", "sans-serif"],
  ["Asta Sans", "sans-serif"],
  ["Erica One", "display"],
  ["Fenix", "serif"],
  ["Engagement", "handwriting"],
  ["Beau Rivage", "handwriting"],
  ["IBM Plex Sans Thai Looped", "sans-serif"],
  ["Devonshire", "handwriting"],
  ["Underdog", "display"],
  ["Sono", "sans-serif"],
  ["Braah One", "sans-serif"],
  ["Cute Font", "display"],
  ["Lovers Quarrel", "handwriting"],
  ["Margarine", "display"],
  ["Texturina", "serif"],
  ["Londrina Outline", "display"],
  ["Passions Conflict", "handwriting"],
  ["Dekko", "handwriting"],
  ["Shippori Antique B1", "sans-serif"],
  ["Karantina", "display"],
  ["Stint Ultra Condensed", "serif"],
  ["BIZ UDMincho", "serif"],
  ["Trispace", "sans-serif"],
  ["Ballet", "handwriting"],
  ["Gorditas", "display"],
  ["Stack Sans Text", "sans-serif"],
  ["Mea Culpa", "handwriting"],
  ["Sree Krushnadevaraya", "serif"],
  ["Comforter", "handwriting"],
  ["Kotta One", "serif"],
  ["Chocolate Classical Sans", "sans-serif"],
  ["Bagel Fat One", "display"],
  ["Dangrek", "display"],
  ["Dorsa", "sans-serif"],
  ["Londrina Shadow", "display"],
  ["Akaya Telivigala", "display"],
  ["Noto Sans Linear A", "sans-serif"],
  ["Noto Sans Gothic", "sans-serif"],
  ["Sura", "serif"],
  ["Noto Sans Osmanya", "sans-serif"],
  ["Tiro Devanagari Sanskrit", "serif"],
  ["Zen Tokyo Zoo", "display"],
  ["Keania One", "display"],
  ["Kaisei HarunoUmi", "serif"],
  ["Junge", "serif"],
  ["Libre Barcode EAN13 Text", "display"],
  ["Joan", "serif"],
  ["Suwannaphum", "serif"],
  ["Momo Signature", "sans-serif"],
  ["Sonsie One", "display"],
  ["Federant", "display"],
  ["Mate SC", "serif"],
  ["Carrois Gothic SC", "sans-serif"],
  ["Edu NSW ACT Cursive", "handwriting"],
  ["Chiron GoRound TC", "sans-serif"],
  ["My Soul", "handwriting"],
  ["Liter", "sans-serif"],
  ["Stint Ultra Expanded", "serif"],
  ["Lugrasimo", "handwriting"],
  ["Jersey 15", "display"],
  ["Faculty Glyphic", "sans-serif"],
  ["Sedan SC", "serif"],
  ["Climate Crisis", "display"],
  ["Arbutus", "serif"],
  ["Spirax", "display"],
  ["Koh Santepheap", "serif"],
  ["Tillana", "display"],
  ["Paprika", "display"],
  ["Gwendolyn", "handwriting"],
  ["Content", "display"],
  ["Reddit Mono", "monospace"],
  ["Port Lligat Slab", "serif"],
  ["Anek Kannada", "sans-serif"],
  ["Sahitya", "serif"],
  ["Gasoek One", "sans-serif"],
  ["Anek Gujarati", "sans-serif"],
  ["Noto Serif Kannada", "serif"],
  ["Ysabeau Infant", "sans-serif"],
  ["Rum Raisin", "sans-serif"],
  ["Montserrat Underline", "sans-serif"],
  ["Condiment", "handwriting"],
  ["Noto Sans Gurmukhi", "sans-serif"],
  ["Seymour One", "sans-serif"],
  ["Rubik Scribble", "display"],
  ["Tiny5", "sans-serif"],
  ["Bilbo", "handwriting"],
  ["Nuosu SIL", "sans-serif"],
  ["Ysabeau", "sans-serif"],
  ["Noto Sans Thaana", "sans-serif"],
  ["Farsan", "display"],
  ["Yuji Boku", "serif"],
  ["Chilanka", "handwriting"],
  ["Text Me One", "sans-serif"],
  ["Glass Antiqua", "display"],
  ["TASA Orbiter", "sans-serif"],
  ["Jacquard 12", "display"],
  ["Castoro Titling", "display"],
  ["Dai Banna SIL", "serif"],
  ["Tourney", "display"],
  ["Stoke", "serif"],
  ["Yaldevi", "sans-serif"],
  ["Alumni Sans Pinstripe", "sans-serif"],
  ["Big Shoulders Stencil", "display"],
  ["New Tegomin", "serif"],
  ["Comforter Brush", "handwriting"],
  ["Noto Sans Tagalog", "sans-serif"],
  ["Offside", "display"],
  ["Cagliostro", "sans-serif"],
  ["Playwrite DE Grund", "handwriting"],
  ["Noto Serif Telugu", "serif"],
  ["Ruwudu", "serif"],
  ["Almendra SC", "serif"],
  ["Tac One", "sans-serif"],
  ["Noto Sans Mahajani", "sans-serif"],
  ["Arsenal SC", "sans-serif"],
  ["Victor Mono", "monospace"],
  ["National Park", "sans-serif"],
  ["LXGW WenKai TC", "handwriting"],
  ["Poor Story", "display"],
  ["Ramaraja", "serif"],
  ["Mozilla Text", "sans-serif"],
  ["Playwrite IS", "handwriting"],
  ["Inika", "serif"],
  ["Water Brush", "handwriting"],
  ["Festive", "handwriting"],
  ["Noto Sans Buhid", "sans-serif"],
  ["Kite One", "sans-serif"],
  ["Mogra", "display"],
  ["Beiruti", "sans-serif"],
  ["Romanesco", "handwriting"],
  ["Marko One", "serif"],
  ["Rubik Iso", "display"],
  ["Noto Sans Batak", "sans-serif"],
  ["Rubik Moonrocks", "display"],
  ["Bruno Ace SC", "display"],
  ["Noto Serif Lao", "serif"],
  ["Noto Sans Samaritan", "sans-serif"],
  ["Edu AU VIC WA NT Hand", "handwriting"],
  ["Autour One", "display"],
  ["Simonetta", "display"],
  ["Orbit", "sans-serif"],
  ["Playwrite IN", "handwriting"],
  ["Uchen", "serif"],
  ["Playwrite CU", "handwriting"],
  ["Noto Serif Sinhala", "serif"],
  ["Ruluko", "sans-serif"],
  ["Tiro Devanagari Marathi", "serif"],
  ["Ojuju", "sans-serif"],
  ["Emblema One", "display"],
  ["Plaster", "display"],
  ["Siemreap", "sans-serif"],
  ["Amiri Quran", "serif"],
  ["Ravi Prakash", "display"],
  ["Reem Kufi Fun", "sans-serif"],
  ["Trykker", "serif"],
  ["Lexend Tera", "sans-serif"],
  ["Micro 5", "display"],
  ["Noto Serif Ahom", "serif"],
  ["Noto Sans Sora Sompeng", "sans-serif"],
  ["Noto Sans Canadian Aboriginal", "sans-serif"],
  ["Galindo", "display"],
  ["Science Gothic", "sans-serif"],
  ["Libre Barcode 39 Extended", "display"],
  ["Noto Serif Tamil", "serif"],
  ["Wittgenstein", "serif"],
  ["Playwrite VN Guides", "handwriting"],
  ["Nabla", "display"],
  ["Bruno Ace", "display"],
  ["Dhurjati", "sans-serif"],
  ["Stalinist One", "display"],
  ["Anek Gurmukhi", "sans-serif"],
  ["Noto Sans Pahawh Hmong", "sans-serif"],
  ["Smokum", "display"],
  ["Bodoni Moda SC", "serif"],
  ["Bungee Hairline", "display"],
  ["Port Lligat Sans", "sans-serif"],
  ["Donegal One", "serif"],
  ["Tiro Gurmukhi", "serif"],
  ["Fascinate Inline", "display"],
  ["Jacques Francois", "serif"],
  ["Moderustic", "sans-serif"],
  ["Elsie Swash Caps", "display"],
  ["Risque", "display"],
  ["Fleur De Leah", "handwriting"],
  ["Encode Sans SC", "sans-serif"],
  ["Noto Sans Tai Viet", "sans-serif"],
  ["Linden Hill", "serif"],
  ["Aref Ruqaa Ink", "serif"],
  ["Stack Sans Headline", "sans-serif"],
  ["Caramel", "handwriting"],
  ["Felipa", "handwriting"],
  ["Tilt Prism", "display"],
  ["Splash", "handwriting"],
  ["Kumar One", "display"],
  ["Inspiration", "handwriting"],
  ["Chela One", "display"],
  ["Piedra", "display"],
  ["Jacques Francois Shadow", "display"],
  ["Meera Inimai", "sans-serif"],
  ["Miss Fajardose", "handwriting"],
  ["Metal", "display"],
  ["Revalia", "display"],
  ["Playwrite AT", "handwriting"],
  ["Libertinus Sans", "sans-serif"],
  ["Momo Trust Display", "sans-serif"],
  ["Dr Sugiyama", "handwriting"],
  ["Monomakh", "display"],
  ["Reem Kufi Ink", "sans-serif"],
  ["Bigelow Rules", "display"],
  ["Tiro Telugu", "serif"],
  ["Diplomata", "display"],
  ["Grey Qo", "handwriting"],
  ["Sirin Stencil", "display"],
  ["Playwrite AU NSW", "handwriting"],
  ["Noto Sans Gunjala Gondi", "sans-serif"],
  ["Oi", "display"],
  ["Noto Rashi Hebrew", "serif"],
  ["Fruktur", "display"],
  ["Galdeano", "sans-serif"],
  ["Mr Bedfort", "handwriting"],
  ["Tulpen One", "display"],
  ["Luxurious Roman", "display"],
  ["BBH Bartle", "sans-serif"],
  ["Konkhmer Sleokchher", "display"],
  ["Playwrite AU SA", "handwriting"],
  ["Ewert", "display"],
  ["Londrina Sketch", "display"],
  ["Passero One", "display"],
  ["Lancelot", "display"],
  ["Updock", "handwriting"],
  ["Rubik Gemstones", "display"],
  ["Vend Sans", "sans-serif"],
  ["Neonderthaw", "handwriting"],
  ["Alumni Sans Collegiate One", "sans-serif"],
  ["Jersey 20", "display"],
  ["Lakki Reddy", "handwriting"],
  ["Ga Maamli", "display"],
  ["Joti One", "display"],
  ["Wellfleet", "serif"],
  ["GFS Neohellenic", "sans-serif"],
  ["Ribeye Marrow", "display"],
  ["Sixtyfour", "monospace"],
  ["New Amsterdam", "sans-serif"],
  ["Playwrite AU QLD", "handwriting"],
  ["Rubik Distressed", "display"],
  ["Babylonica", "handwriting"],
  ["Anek Odia", "sans-serif"],
  ["Bungee Outline", "display"],
  ["Flow Rounded", "display"],
  ["Geostar Fill", "display"],
  ["Manufacturing Consent", "display"],
  ["Blaka", "display"],
  ["Preahvihear", "sans-serif"],
  ["Bitcount Single", "display"],
  ["BioRhyme Expanded", "serif"],
  ["Send Flowers", "handwriting"],
  ["Hubballi", "sans-serif"],
  ["Momo Trust Sans", "sans-serif"],
  ["Playwrite US Modern", "handwriting"],
  ["WDXL Lubrifont TC", "sans-serif"],
  ["Noto Sans Anatolian Hieroglyphs", "sans-serif"],
  ["Sofadi One", "display"],
  ["Noto Serif Gujarati", "serif"],
  ["Rubik Pixels", "display"],
  ["Ancizar Serif", "serif"],
  ["Praise", "handwriting"],
  ["LXGW WenKai Mono TC", "monospace"],
  ["Playwrite PL", "handwriting"],
  ["Almendra Display", "display"],
  ["Story Script", "sans-serif"],
  ["Ranga", "display"],
  ["Tapestry", "handwriting"],
  ["Chiron Hei HK", "sans-serif"],
  ["Noto Serif Armenian", "serif"],
  ["Playwrite GB S", "handwriting"],
  ["Diplomata SC", "display"],
  ["Bacasime Antique", "serif"],
  ["Shizuru", "display"],
  ["Huninn", "sans-serif"],
  ["Epunda Sans", "sans-serif"],
  ["Bonbon", "handwriting"],
  ["Mozilla Headline", "sans-serif"],
  ["Jim Nightshade", "handwriting"],
  ["Princess Sofia", "handwriting"],
  ["Libertinus Math", "display"],
  ["Molle", "handwriting"],
  ["Playpen Sans Arabic", "handwriting"],
  ["Atkinson Hyperlegible Mono", "sans-serif"],
  ["Griffy", "display"],
  ["Bahiana", "display"],
  ["Kirang Haerang", "display"],
  ["Ponomar", "display"],
  ["Noto Sans Tangsa", "sans-serif"],
  ["Noto Sans Hanunoo", "sans-serif"],
  ["Iansui", "handwriting"],
  ["Agu Display", "display"],
  ["Butcherman", "display"],
  ["Foldit", "display"],
  ["Peddana", "serif"],
  ["Tsukimi Rounded", "sans-serif"],
  ["Jacquard 24", "display"],
  ["Love Light", "handwriting"],
  ["Sedan", "serif"],
  ["Flavors", "display"],
  ["Noto Sans Adlam", "sans-serif"],
  ["Kumar One Outline", "display"],
  ["Noto Serif Khmer", "serif"],
  ["Noto Sans Lao Looped", "sans-serif"],
  ["Tiro Kannada", "serif"],
  ["Gideon Roman", "display"],
  ["Mrs Sheppards", "handwriting"],
  ["Alumni Sans Inline One", "display"],
  ["Noto Sans Javanese", "sans-serif"],
  ["Bitcount Prop Single", "display"],
  ["Ubuntu Sans Mono", "monospace"],
  ["Lunasima", "sans-serif"],
  ["Libertinus Serif", "serif"],
  ["Sixtyfour Convergence", "monospace"],
  ["Flow Block", "display"],
  ["Snippet", "sans-serif"],
  ["Rubik Glitch Pop", "display"],
  ["Are You Serious", "handwriting"],
  ["Rubik Vinyl", "display"],
  ["Purple Purse", "display"],
  ["Gidugu", "sans-serif"],
  ["Diphylleia", "serif"],
  ["Oldenburg", "display"],
  ["Kings", "handwriting"],
  ["Noto Sans Nag Mundari", "sans-serif"],
  ["Noto Sans Sunuwar", "sans-serif"],
  ["Bitcount Grid Single", "display"],
  ["Annapurna SIL", "serif"],
  ["Hanalei Fill", "display"],
  ["Ancizar Sans", "sans-serif"],
  ["Rubik Beastly", "display"],
  ["Edu AU VIC WA NT Pre", "handwriting"],
  ["Twinkle Star", "handwriting"],
  ["WDXL Lubrifont JP N", "sans-serif"],
  ["Tai Heritage Pro", "serif"],
  ["Danfo", "serif"],
  ["Edu VIC WA NT Beginner", "handwriting"],
  ["Rubik Burned", "display"],
  ["Jacquarda Bastarda 9", "display"],
  ["Edu NSW ACT Foundation", "handwriting"],
  ["WDXL Lubrifont SC", "sans-serif"],
  ["Big Shoulders Inline", "display"],
  ["Rubik 80s Fade", "display"],
  ["TASA Explorer", "sans-serif"],
  ["Taprom", "display"],
  ["Trochut", "display"],
  ["Butterfly Kids", "handwriting"],
  ["Matemasie", "sans-serif"],
  ["Noto Serif Ethiopic", "serif"],
  ["Tiro Tamil", "serif"],
  ["Geostar", "display"],
  ["Sassy Frass", "handwriting"],
  ["Rubik Spray Paint", "display"],
  ["Bungee Tint", "display"],
  ["Gidole", "sans-serif"],
  ["Iosevka Charon", "monospace"],
  ["Noto Serif Tangut", "serif"],
  ["Protest Guerrilla", "display"],
  ["Chenla", "display"],
  ["Playwrite HU", "handwriting"],
  ["Noto Serif Vithkuqi", "serif"],
  ["Explora", "handwriting"],
  ["Noto Sans Coptic", "sans-serif"],
  ["Edu AU VIC WA NT Dots", "handwriting"],
  ["Noto Sans Carian", "sans-serif"],
  ["Grechen Fuemen", "handwriting"],
  ["Redacted Script", "display"],
  ["Suravaram", "serif"],
  ["Zen Loop", "display"],
  ["Noto Sans Syriac", "sans-serif"],
  ["Playwrite DK Loopet", "handwriting"],
  ["Iosevka Charon Mono", "monospace"],
  ["Cascadia Mono", "sans-serif"],
  ["Alumni Sans SC", "sans-serif"],
  ["Langar", "display"],
  ["Black And White Picture", "display"],
  ["Bitcount Grid Double", "display"],
  ["Combo", "display"],
  ["Aubrey", "display"],
  ["Rubik Puddles", "display"],
  ["Playwrite NO", "handwriting"],
  ["Moulpali", "sans-serif"],
  ["Noto Serif Tibetan", "serif"],
  ["Noto Sans New Tai Lue", "sans-serif"],
  ["Bitcount", "display"],
  ["Playwrite AR", "handwriting"],
  ["Sekuya", "display"],
  ["M PLUS Code Latin", "sans-serif"],
  ["Cossette Titre", "sans-serif"],
  ["Playwrite RO", "handwriting"],
  ["Winky Rough", "sans-serif"],
  ["Playwrite HR", "handwriting"],
  ["Workbench", "monospace"],
  ["Kalnia Glaze", "display"],
  ["Playwrite MX Guides", "handwriting"],
  ["Kolker Brush", "handwriting"],
  ["Vibes", "display"],
  ["Playwrite CA", "handwriting"],
  ["Elms Sans", "sans-serif"],
  ["Noto Sans Syloti Nagri", "sans-serif"],
  ["Bahianita", "display"],
  ["Libertinus Mono", "monospace"],
  ["Cherish", "handwriting"],
  ["Ruge Boogie", "handwriting"],
  ["Noto Sans Shavian", "sans-serif"],
  ["Labrada", "serif"],
  ["Playwrite DE SAS", "handwriting"],
  ["Noto Sans Cypro Minoan", "sans-serif"],
  ["Noto Sans Nandinagari", "sans-serif"],
  ["Noto Sans Mongolian", "sans-serif"],
  ["Chokokutai", "display"],
  ["Hind Mysuru", "sans-serif"],
  ["Noto Sans Multani", "sans-serif"],
  ["Chiron Sung HK", "serif"],
  ["Snowburst One", "display"],
  ["LXGW Marker Gothic", "sans-serif"],
  ["Noto Sans Adlam Unjoined", "sans-serif"],
  ["Savate", "sans-serif"],
  ["Estonia", "handwriting"],
  ["Tagesschrift", "display"],
  ["Rock 3D", "display"],
  ["Asimovian", "sans-serif"],
  ["Puppies Play", "handwriting"],
  ["Gajraj One", "display"],
  ["Playwrite PE", "handwriting"],
  ["Petemoss", "handwriting"],
  ["Stack Sans Notch", "sans-serif"],
  ["Playwrite NL", "handwriting"],
  ["Moirai One", "display"],
  ["Noto Sans Glagolitic", "sans-serif"],
  ["Noto Serif Balinese", "serif"],
  ["Epunda Slab", "serif"],
  ["Noto Serif Toto", "serif"],
  ["Noto Sans Duployan", "sans-serif"],
  ["Slackside One", "handwriting"],
  ["Noto Sans Kaithi", "sans-serif"],
  ["Phetsarath", "sans-serif"],
  ["Playpen Sans Hebrew", "handwriting"],
  ["Triodion", "display"],
  ["Bitcount Grid Single Ink", "display"],
  ["Playpen Sans Deva", "handwriting"],
  ["Noto Sans Takri", "sans-serif"],
  ["Palette Mosaic", "display"],
  ["Noto Sans Balinese", "sans-serif"],
  ["Noto Serif Yezidi", "serif"],
  ["Bitcount Single Ink", "display"],
  ["Bitcount Grid Double Ink", "display"],
  ["Menbere", "sans-serif"],
  ["Noto Sans Warang Citi", "sans-serif"],
  ["Bitcount Prop Double Ink", "display"],
  ["Noto Sans Yi", "sans-serif"],
  ["Jaini", "display"],
  ["Intel One Mono", "monospace"],
  ["BBH Bogle", "sans-serif"],
  ["Ingrid Darling", "handwriting"],
  ["Playwrite BE VLG", "handwriting"],
  ["Bitcount Prop Single Ink", "display"],
  ["Playwrite ZA", "handwriting"],
  ["Rubik Microbe", "display"],
  ["Noto Sans Cherokee", "sans-serif"],
  ["Lilex", "monospace"],
  ["Edu SA Hand", "handwriting"],
  ["Karla Tamil Inclined", "sans-serif"],
  ["Playwrite IT Moderna", "handwriting"],
  ["Bitcount Ink", "display"],
  ["Bitcount Prop Double", "display"],
  ["Noto Sans Syriac Eastern", "sans-serif"],
  ["Noto Traditional Nushu", "sans-serif"],
  ["Noto Sans Vithkuqi", "sans-serif"],
  ["Bytesized", "sans-serif"],
  ["Noto Sans Marchen", "sans-serif"],
  ["Noto Sans Old Italic", "sans-serif"],
  ["Mingzat", "sans-serif"],
  ["Noto Sans Palmyrene", "sans-serif"],
  ["Playwrite FR Moderne", "handwriting"],
  ["BBH Hegarty", "sans-serif"],
  ["SUSE Mono", "sans-serif"],
  ["Moo Lah Lah", "display"],
  ["Datatype", "monospace"],
  ["Parastoo", "serif"],
  ["Noto Serif Dogra", "serif"],
  ["Hanalei", "display"],
  ["Shafarik", "display"],
  ["Playwrite MX", "handwriting"],
  ["Sirivennela", "sans-serif"],
  ["Noto Serif Myanmar", "serif"],
  ["Rubik Broken Fax", "display"],
  ["Noto Sans Old Hungarian", "sans-serif"],
  ["Coral Pixels", "display"],
  ["Syne Tactile", "display"],
  ["Matangi", "sans-serif"],
  ["Playwrite PT", "handwriting"],
  ["Ole", "handwriting"],
  ["Playwrite BE WAL", "handwriting"],
  ["Playpen Sans Thai", "handwriting"],
  ["Rubik Maps", "display"],
  ["Playwrite DK Uloopet Guides", "handwriting"],
  ["Grandiflora One", "serif"],
  ["Alyamama", "serif"],
  ["Noto Serif Oriya", "serif"],
  ["Noto Sans Old North Arabian", "sans-serif"],
  ["Rubik Marker Hatch", "display"],
  ["Noto Sans Elbasan", "sans-serif"],
  ["Noto Sans Egyptian Hieroglyphs", "sans-serif"],
  ["Playwrite NZ Basic", "handwriting"],
  ["Linefont", "display"],
  ["Noto Serif NP Hmong", "serif"],
  ["Noto Sans NKo", "sans-serif"],
  ["Yuji Hentaigana Akari", "handwriting"],
  ["Noto Serif Makasar", "serif"],
  ["Sankofa Display", "sans-serif"],
  ["Edu QLD Beginner", "handwriting"],
  ["Rubik Doodle Triangles", "display"],
  ["Rubik Storm", "display"],
  ["Rubik Lines", "display"],
  ["Noto Znamenny Musical Notation", "sans-serif"],
  ["Jaini Purva", "display"],
  ["Noto Sans Medefaidrin", "sans-serif"],
  ["Noto Sans Bamum", "sans-serif"],
  ["Noto Serif Gurmukhi", "serif"],
  ["Playwrite HR Lijeva", "handwriting"],
  ["UoqMunThenKhung", "serif"],
  ["Noto Sans Tai Le", "sans-serif"],
  ["Noto Sans Tifinagh", "sans-serif"],
  ["Noto Serif Khitan Small Script", "serif"],
  ["Playwrite AU TAS", "handwriting"],
  ["Noto Sans Avestan", "sans-serif"],
  ["Blaka Hollow", "display"],
  ["Tuffy", "sans-serif"],
  ["Exile", "display"],
  ["Lisu Bosa", "serif"],
  ["Noto Sans Indic Siyaq Numbers", "sans-serif"],
  ["Playwrite CO Guides", "handwriting"],
  ["Noto Sans Lisu", "sans-serif"],
  ["Noto Sans Ol Chiki", "sans-serif"],
  ["Playwrite VN", "handwriting"],
  ["Playwrite ES", "handwriting"],
  ["Maname", "serif"],
  ["Noto Sans Old Permic", "sans-serif"],
  ["Blaka Ink", "display"],
  ["Noto Sans Newa", "sans-serif"],
  ["Playwrite DK Uloopet", "handwriting"],
  ["Noto Serif Ottoman Siyaq", "serif"],
  ["Playwrite SK", "handwriting"],
  ["Playwrite DE LA", "handwriting"],
  ["Narnoor", "sans-serif"],
  ["Noto Serif Todhri", "serif"],
  ["Warnes", "display"],
  ["Playwrite CO", "handwriting"],
  ["Noto Sans Osage", "sans-serif"],
  ["Kedebideri", "sans-serif"],
  ["Edu NSW ACT Hand Pre", "handwriting"],
  ["Namdhinggo", "serif"],
  ["Noto Sans Khojki", "sans-serif"],
  ["Rubik Maze", "display"],
  ["Playwrite AU VIC", "handwriting"],
  ["Ponnala", "display"],
  ["Jacquard 12 Charted", "display"],
  ["Playwrite NZ", "handwriting"],
  ["Libertinus Serif Display", "display"],
  ["Noto Serif Hentaigana", "serif"],
  ["Wavefont", "display"],
  ["Playwrite GB J", "handwriting"],
  ["Noto Serif Grantha", "serif"],
  ["Amarna", "sans-serif"],
  ["Gveret Levin", "handwriting"],
  ["Noto Sans Cuneiform", "sans-serif"],
  ["Noto Sans Tagbanwa", "sans-serif"],
  ["Edu AU VIC WA NT Guides", "handwriting"],
  ["Noto Sans Sundanese", "sans-serif"],
  ["Noto Sans Brahmi", "sans-serif"],
  ["Padyakke Expanded One", "serif"],
  ["Edu AU VIC WA NT Arrows", "handwriting"],
  ["Noto Sans Cham", "sans-serif"],
  ["Playwrite CZ", "handwriting"],
  ["Playwrite CU Guides", "handwriting"],
  ["Noto Sans Lydian", "sans-serif"],
  ["Edu QLD Hand", "handwriting"],
  ["Noto Sans Tai Tham", "sans-serif"],
  ["Noto Sans Old Persian", "sans-serif"],
  ["Betania Patmos", "handwriting"],
  ["Noto Sans Miao", "sans-serif"],
  ["Idiqlat", "serif"],
  ["Noto Sans Inscriptional Pahlavi", "sans-serif"],
  ["Noto Sans Imperial Aramaic", "sans-serif"],
  ["Karla Tamil Upright", "sans-serif"],
  ["Micro 5 Charted", "display"],
  ["Playwrite CL", "handwriting"],
  ["Playwrite NG Modern", "handwriting"],
  ["Libertinus Keyboard", "display"],
  ["Noto Sans Zanabazar Square", "sans-serif"],
  ["Noto Serif Old Uyghur", "serif"],
  ["Jacquard 24 Charted", "display"],
  ["Allkin", "display"],
  ["Noto Sans Buginese", "sans-serif"],
  ["Pochaevsk", "display"],
  ["Noto Sans SignWriting", "sans-serif"],
  ["Kay Pho Du", "serif"],
  ["Noto Sans Old South Arabian", "sans-serif"],
  ["Noto Sans NKo Unjoined", "sans-serif"],
  ["Playwrite ES Deco", "handwriting"],
  ["Betania Patmos In GDL", "handwriting"],
  ["Noto Sans Sogdian", "sans-serif"],
  ["Noto Sans Wancho", "sans-serif"],
  ["Noto Sans Sharada", "sans-serif"],
  ["Playwrite TZ", "handwriting"],
  ["Noto Sans Runic", "sans-serif"],
  ["Cossette Texte", "sans-serif"],
  ["Playwrite NZ Basic Guides", "handwriting"],
  ["Noto Sans Chakma", "sans-serif"],
  ["Bpmf Zihi Kai Std", "sans-serif"],
  ["Kanchenjunga", "sans-serif"],
  ["Betania Patmos In", "handwriting"],
  ["Ramsina", "serif"],
  ["Jersey 15 Charted", "display"],
  ["Playwrite PL Guides", "handwriting"],
  ["Noto Sans Bassa Vah", "sans-serif"],
  ["Noto Sans Linear B", "sans-serif"],
  ["Playwrite PT Guides", "handwriting"],
  ["Edu VIC WA NT Hand Pre", "handwriting"],
  ["Playwrite ID", "handwriting"],
  ["Noto Sans Mayan Numerals", "sans-serif"],
  ["Bpmf Huninn", "sans-serif"],
  ["Playwrite PE Guides", "handwriting"],
  ["Betania Patmos GDL", "handwriting"],
  ["Noto Sans Bhaiksuki", "sans-serif"],
  ["Noto Serif Dives Akuru", "serif"],
  ["Noto Sans Vai", "sans-serif"],
  ["Edu VIC WA NT Hand", "handwriting"],
  ["Noto Sans Hatran", "sans-serif"],
  ["Jersey 25 Charted", "display"],
  ["Noto Sans Phoenician", "sans-serif"],
  ["Noto Sans Elymaic", "sans-serif"],
  ["Noto Sans Inscriptional Parthian", "sans-serif"],
  ["Bpmf Iansui", "handwriting"],
  ["Noto Sans Tamil Supplement", "sans-serif"],
  ["Noto Sans Kawi", "sans-serif"],
  ["Playwrite BR", "handwriting"],
  ["Cause", "handwriting"],
  ["Noto Sans Caucasian Albanian", "sans-serif"],
  ["Noto Sans Hanifi Rohingya", "sans-serif"],
  ["Noto Sans Syriac Western", "sans-serif"],
  ["Noto Sans Modi", "sans-serif"],
  ["Noto Sans Psalter Pahlavi", "sans-serif"],
  ["Playwrite IT Trad", "handwriting"],
  ["Jersey 20 Charted", "display"],
  ["Jersey 10 Charted", "display"],
  ["Noto Sans Rejang", "sans-serif"],
  ["Noto Sans Saurashtra", "sans-serif"],
  ["Noto Sans Old Turkic", "sans-serif"],
  ["Playwrite US Trad Guides", "handwriting"],
  ["Noto Sans Ugaritic", "sans-serif"],
  ["Noto Sans Grantha", "sans-serif"],
  ["Noto Sans Khudawadi", "sans-serif"],
  ["Noto Sans Kayah Li", "sans-serif"],
  ["Yarndings 20", "display"],
  ["Noto Sans Mandaic", "sans-serif"],
  ["Noto Sans Mende Kikakui", "sans-serif"],
  ["Noto Sans Nushu", "sans-serif"],
  ["Noto Sans Mro", "sans-serif"],
  ["Noto Sans Ogham", "sans-serif"],
  ["Noto Sans Deseret", "sans-serif"],
  ["Noto Sans Cypriot", "sans-serif"],
  ["Yuji Hentaigana Akebono", "handwriting"],
  ["Yarndings 12", "display"],
  ["Playwrite DE VA", "handwriting"],
  ["Noto Sans Siddham", "sans-serif"],
  ["Playwrite FR Trad", "handwriting"],
  ["Noto Sans Pau Cin Hau", "sans-serif"],
  ["Noto Sans Old Sogdian", "sans-serif"],
  ["Noto Sans Tirhuta", "sans-serif"],
  ["Noto Sans Nabataean", "sans-serif"],
  ["Noto Sans Chorasmian", "sans-serif"],
  ["Noto Sans Limbu", "sans-serif"],
  ["Tirra", "sans-serif"],
  ["Jacquarda Bastarda 9 Charted", "display"],
  ["Yarndings 12 Charted", "display"],
  ["Noto Sans Manichaean", "sans-serif"],
  ["Noto Sans Soyombo", "sans-serif"],
  ["Noto Sans Lepcha", "sans-serif"],
  ["Yarndings 20 Charted", "display"],
  ["Playwrite IN Guides", "handwriting"],
  ["Playwrite GB J Guides", "handwriting"],
  ["Noto Sans PhagsPa", "sans-serif"],
  ["Playwrite DE Grund Guides", "handwriting"],
  ["Noto Sans Masaram Gondi", "sans-serif"],
  ["Noto Sans Kharoshthi", "sans-serif"],
  ["Playwrite TZ Guides", "handwriting"],
  ["Playwrite AU VIC Guides", "handwriting"],
  ["Playwrite BE WAL Guides", "handwriting"],
  ["Playwrite IE Guides", "handwriting"],
  ["Noto Sans Lycian", "sans-serif"],
  ["Playwrite ES Deco Guides", "handwriting"],
  ["Playwrite NZ Guides", "handwriting"],
  ["Playwrite DE VA Guides", "handwriting"],
  ["Playwrite BR Guides", "handwriting"],
  ["Playwrite NL Guides", "handwriting"],
  ["Playwrite FR Moderne Guides", "handwriting"],
  ["Playwrite ZA Guides", "handwriting"],
  ["Playwrite US Modern Guides", "handwriting"],
  ["Playwrite HU Guides", "handwriting"],
  ["Playwrite FR Trad Guides", "handwriting"],
  ["Playwrite IT Moderna Guides", "handwriting"],
  ["Playwrite IT Trad Guides", "handwriting"],
  ["Playwrite CL Guides", "handwriting"],
  ["Playwrite ID Guides", "handwriting"],
  ["Playwrite AU SA Guides", "handwriting"],
  ["Playwrite DK Loopet Guides", "handwriting"],
  ["Playwrite AU NSW Guides", "handwriting"],
  ["Playwrite AR Guides", "handwriting"],
  ["Playwrite AT Guides", "handwriting"],
  ["Playwrite DE LA Guides", "handwriting"],
  ["Playwrite NG Modern Guides", "handwriting"],
  ["Playwrite IS Guides", "handwriting"],
  ["Playwrite GB S Guides", "handwriting"],
  ["Playwrite HR Lijeva Guides", "handwriting"],
  ["Playwrite ES Guides", "handwriting"],
  ["Playwrite AU TAS Guides", "handwriting"],
  ["Playwrite RO Guides", "handwriting"],
  ["Playwrite AU QLD Guides", "handwriting"],
  ["Playwrite BE VLG Guides", "handwriting"],
  ["Playwrite DE SAS Guides", "handwriting"],
  ["Playwrite CA Guides", "handwriting"],
  ["Playwrite SK Guides", "handwriting"],
  ["Playwrite CZ Guides", "handwriting"],
  ["Playwrite HR Guides", "handwriting"],
  ["Playwrite NO Guides", "handwriting"],
];
